In [1]:
import numpy as np #np is the alias name to numpy 

In [2]:
my_list=[1,2,3,4,5]

In [6]:
print(my_list)

[1, 2, 3, 4, 5]


In [3]:
type(my_list)

list

In [ ]:
#list will be converted to an array by using a function called - np.array()

In [4]:
arr=np.array(my_list)

In [5]:
print(arr) #1 dimentional numpy array 

[1 2 3 4 5]


In [7]:
type(arr) 

numpy.ndarray

In [8]:
#multidimentional numpy array 
my_list_1=[1,2,3,4,5]
my_list_2=[3,5,7,9,0]
my_list_3=[2,3,1,5,9]

arr_new=np.array([my_list_1,my_list_2,my_list_3])

In [9]:
print(arr_new) #2 dimentional numpy array with 3 rows and 5 columns 

[[1 2 3 4 5]
 [3 5 7 9 0]
 [2 3 1 5 9]]


In [10]:
arr_new.shape #.shape will show the number of rows and number of columns 

(3, 5)

In [11]:
arr_new.reshape(5,3) #5,3 means - 5*3 i.e. 15 elements in the numpy array

array([[1, 2, 3],
       [4, 5, 3],
       [5, 7, 9],
       [0, 2, 3],
       [1, 5, 9]])

In [12]:
arr_new.reshape(5,4) #5,4 means 5*4 i.e 20 elements in the numpy array 

ValueError: cannot reshape array of size 15 into shape (5,4)

In [13]:
#generating numbers using numpy
a=np.arange(0,15) #.arange(0,15) will generate numbers between 0 to 15 (15 will be exclusive)

In [14]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
b=np.arange(0,15,3) #3 is the step size 

In [16]:
print(b)

[ 0  3  6  9 12]


In [17]:
c=np.linspace(1,10,50) #here 50 is the number of output that we need from this given range
#here 10 or the stopping point will not be exclusive in nature

In [18]:
print(c)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [19]:
d=np.linspace(1,10,75) #here 75 is the number of outcomes needed 

In [20]:
print(d)

[ 1.          1.12162162  1.24324324  1.36486486  1.48648649  1.60810811
  1.72972973  1.85135135  1.97297297  2.09459459  2.21621622  2.33783784
  2.45945946  2.58108108  2.7027027   2.82432432  2.94594595  3.06756757
  3.18918919  3.31081081  3.43243243  3.55405405  3.67567568  3.7972973
  3.91891892  4.04054054  4.16216216  4.28378378  4.40540541  4.52702703
  4.64864865  4.77027027  4.89189189  5.01351351  5.13513514  5.25675676
  5.37837838  5.5         5.62162162  5.74324324  5.86486486  5.98648649
  6.10810811  6.22972973  6.35135135  6.47297297  6.59459459  6.71621622
  6.83783784  6.95945946  7.08108108  7.2027027   7.32432432  7.44594595
  7.56756757  7.68918919  7.81081081  7.93243243  8.05405405  8.17567568
  8.2972973   8.41891892  8.54054054  8.66216216  8.78378378  8.90540541
  9.02702703  9.14864865  9.27027027  9.39189189  9.51351351  9.63513514
  9.75675676  9.87837838 10.        ]


In [23]:
#generating random numbers using numpy 
np.random.rand(3,4) #here 3 indicates the number of rows and 4 indicates the number of columns
#here by default the range will be between 0-1 (1 being exclusive)

array([[0.57941764, 0.82501229, 0.33880607, 0.66686929],
       [0.15907241, 0.93639572, 0.67844219, 0.30979641],
       [0.78588205, 0.1607923 , 0.27632795, 0.67682507]])

In [ ]:
#Create a 2D array with 4 rows and 5 columns and values ranging between 0-1 (1 being exclusive)

In [24]:
np.random.rand(4,5)

array([[0.86428866, 0.17697894, 0.97363973, 0.50904749, 0.32455914],
       [0.40879022, 0.86953565, 0.54936434, 0.518695  , 0.75945769],
       [0.78712217, 0.93761249, 0.80539782, 0.95328853, 0.0339459 ],
       [0.13779069, 0.64237158, 0.92721175, 0.90241679, 0.19577588]])

In [32]:
np.random.randint(1,10) #here 1-10 is the range and again 10 will be exclusive

2

In [33]:
np.random.randint(1,10,3) #here 3 indicates the number of output in the given range

array([6, 8, 7])

In [34]:
#numerical analysis using numpy
a=np.array([1,2,3,4,5])

In [35]:
print("adding 1 to each element",a+1)
print("multiply 5 to each element",a*5)
print("subtracting 2 from each element",a-2)
print("squaring all the elements",a**2)

adding 1 to each element [2 3 4 5 6]
multiply 5 to each element [ 5 10 15 20 25]
subtracting 2 from each element [-1  0  1  2  3]
squaring all the elements [ 1  4  9 16 25]


In [36]:
new_arr=np.array([[1,5,7],[4,7,2],[3,1,9]])

In [37]:
print(new_arr)

[[1 5 7]
 [4 7 2]
 [3 1 9]]


In [38]:
new_arr.shape

(3, 3)

In [39]:
print("largest element from the matrix", new_arr.max()) #.max() will give the largest number
print("smallest element from the matrix", new_arr.min()) #.min() will give the smallest number
print("sum of all the elements from the matrix", new_arr.sum()) #.sum() will give sum of all the elements

largest element from the matrix 9
smallest element from the matrix 1
sum of all the elements from the matrix 39


In [40]:
print("transpose of the matrix",new_arr.T) #.T will give the transpose (r-->c and vice versa)

transpose of the matrix [[1 4 3]
 [5 7 1]
 [7 2 9]]


In [41]:
mat_1=np.array([[1,2],[3,4]])
mat_2=np.array([[4,3],[2,1]])

print("adding the metrics together",mat_1+mat_2)
print("multiplying the metrics together",mat_1*mat_2)

adding the metrics together [[5 5]
 [5 5]]
multiplying the metrics together [[4 6]
 [6 4]]
